name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Convert GitHub username to lowercase
      run: echo "GHCR_USER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Extract repository name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f 2)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GHCR_USER --password-stdin

    - name: Build and push jammy-300-amazonlinux
      run: |
        dockerfile="dockerfiles/jammy-300-amazonlinux"
        imagename="jammy-300-amazonlinux"
        echo "Building and pushing $imagename"
        docker build -t ghcr.io/${{ env.GHCR_USER }}/$REPO_NAME:$imagename -f $dockerfile .
        docker push ghcr.io/${{ env.GHCR_USER }}/$REPO_NAME:$imagename

    - name: Build and push jammy-300-alpine
      run: |
        dockerfile="dockerfiles/jammy-300-alpine"
        imagename="jammy-300-alpine"
        echo "Building and pushing $imagename"
        docker build -t ghcr.io/${{ env.GHCR_USER }}/$REPO_NAME:$imagename -f $dockerfile .
        docker push ghcr.io/${{ env.GHCR_USER }}/$REPO_NAME:$imagename
